apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
  namespace: tp-kubernetes
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tp-worker
  template:    
    metadata:
      name: tp-worker
      namespace: tp-kubernetes
      labels:
        app: tp-worker
        role-db: client-postgres
        role-redis: client-redis
    spec:
      containers:
        - name: worker
          image: worker-image
          imagePullPolicy: Never
          resources:
            limits:
              cpu: "100m"
              memory: "128Mi"