services:
  web:
    image: nginx
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    ports:
      - "80:80"
    # volumes:
    #   - "./html:/usr/share/nginx/html"
    depends_on:
      - db
  db:
    image: "postgres:latest"
    environment:
      POSTGRES_DB: exempledb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - "db-data:/usr/postgres/data"
volumes:
  db-data: null

