apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: db-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "password"
        - name: MYSQL_DATABASE
          value: "mydb"
        - name: MYSQL_USER
          value: "user"
        - name: MYSQL_PASSWORD
          value: "password"
        command: ["/bin/bash", "-c", "if [ -d /var/lib/mysql ]; then echo 'MySQL data directory already initialized'; else echo 'Initializing MySQL data directory'; mysqld --initialize-insecure; fi && exec mysqld"]
        volumeMounts:
        - mountPath: "/var/lib/mysql"
          name: mysql-storage
        resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: pvc-mysql
