apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mysql
  namespace: db-demo
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data-mysql/mysql"
