apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
spec:
  containers:
  - name: container-nginx
    image: nginx
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
  # - name: container-db
  #   image: mysql
  #   resources:
  #     limits:
  #       memory: "128Mi"
  #       cpu: "500m"
  #   ports:
  #     - containerPort: 3306
