services:

  redis:
    image: redis:5.0-alpine3.10
    volumes:
      - "./redis-check:/redis-check"
      #- "data-redis:/data"
    networks:
      - redis-network
    healthcheck:
      test: /redis-check/script.sh
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 5s
  db:
    image: postgres:9.4
    volumes:
      - "data-postgres:/var/lib/postgresql/data"
      - "./postgres-check:/postgres-check"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - redis-network
    healthcheck:
      test: /postgres-check/script.sh
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 5s

  vote:
    build: ./vote
    ports:
      - "80:80"
    depends_on:
      - redis
    networks:
      - redis-network
    
  result:
    build: ./result
    ports:
      - "4000:4000"
    depends_on:
      - db
    networks:
      - postgres-network
    
  worker:
    build: ./worker
    depends_on:
      - db
      - redis
    networks:
      - postgres-network
      - redis-network

networks:
  redis-network:
  postgres-network:

volumes:
  data-postgres:
  data-redis:
