apiVersion: apps/v1
kind: Deployment
metadata:
  name: emptydir-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      name: myapp
  template:
    metadata:
      name: myapp
      labels:
        name: myapp
    spec:
      containers:
        - name: container-nginx
          image: nginx
          volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: html-volume
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:    
            - containerPort: 80
      volumes:
        - name: html-volume
          emptyDir: {}

